export const words = [
    "the", "of", "and", "to", "a", "in", "that", "is", "was", "he", "for", "it", "with",
    "as", "his", "on", "be", "at", "by", "i", "this", "had", "not", "are", "but", "from",
    "or", "have", "an", "they", "which", "one", "you", "were", "her", "all", "she", "there",
    "would", "their", "we", "him", "been", "has", "when", "who", "will", "no", "more", "if",
    "out", "so", "said", "what", "up", "its", "about", "into", "than", "them", "can", "only",
    "other", "new", "some", "could", "time", "these", "two", "may", "then", "do", "first",
    "any", "my", "now", "such", "like", "our", "over", "man", "me", "even", "most", "made",
    "after", "also", "did", "many", "before", "must", "through", "back", "years", "where",
    "much", "your", "way", "well", "down", "should", "because", "each", "just", "those",
    "people", "mr", "how", "too", "little", "state", "good", "very", "make", "world",
    "still", "own", "see", "men", "work", "long", "get", "here", "between", "both", "life",
    "being", "under", "never", "day", "same", "another", "know", "while", "last", "might",
    "us", "great", "old", "year", "off", "come", "since", "against", "go", "came", "right",
    "used", "take", "three", "himself", "house", "use", "during", "without", "again",
    "place", "around", "however", "home", "small", "found", "thought", "went", "say",
    "part", "once", "general", "upon", "few", "high", "every", "something", "nothing",
    "yet", "though", "always", "believe", "today", "large", "money", "order", "face",
    "next", "public", "rather", "often", "love", "together", "kind", "children",
    "open", "service", "name", "number", "city", "business", "white", "example", "begin",
    "give", "look", "family", "group", "country", "help", "power", "against", "hand",
    "change", "different", "night", "end", "question", "word", "school", "story",
    "study", "important", "side", "far", "head", "long", "eyes", "ever", "area", "world",
    "young", "girl", "boy", "run", "move", "body", "music", "learn", "program", "game",
    "water", "food", "air", "mother", "father", "hour", "idea", "moment", "law", "care",
    "book", "system", "line", "center", "friend", "team", "hour", "voice", "woman",
    "light", "others", "stop", "talk", "mind", "play", "war", "history", "service",
    "market", "price", "research", "science", "road", "street", "form", "room", "train",
    "wait", "parent", "college", "teacher", "class", "office", "result", "health",
    "reason", "value", "union", "sense", "period", "society", "police", "military",
    "future", "past", "truth", "art", "morning", "evening", "week", "month", "season",
    "language", "nature", "chance", "force", "energy", "position", "south", "north",
    "east", "west", "land", "sea", "ship", "river", "mountain", "tree", "plant", "animal",
    "dog", "cat", "bird", "fish", "horse", "cow", "bear", "food", "bread", "milk", "fruit",
    "apple", "orange", "banana", "grape", "rice", "meat", "egg", "sugar", "salt", "tea",
    "coffee", "beer", "wine", "money", "bank", "shop", "trade", "job", "work", "labor",
    "machine", "computer", "phone", "internet", "film", "book", "newspaper", "magazine",
    "song", "dance", "art", "painting", "picture", "color", "sound", "voice", "dream",
    "love", "peace", "death", "life", "hope", "fear", "joy", "pain", "happiness", "sadness",
    "freedom", "justice", "honor", "strength", "beauty", "truth",

    "ask", "become", "call", "create", "find", "keep", "let", "live", "need", "put", "show", "start", "tell", "try", "turn", "walk", "write", "bring", "buy", "catch", "choose", "cut", "drive", "eat", "fall", "feel", "fight", "fly", "forget", "grow", "hear", "hide", "hit", "hold", "hurt", "jump", "kill", "lead", "leave", "lose", "mean", "meet", "pay", "read", "ride", "ring", "rise", "seek", "sell", "send", "set", "shake", "shoot", "shout", "shut", "sing", "sit", "sleep", "smell", "speak", "spend", "stand", "swim", "teach", "think", "throw", "understand", "wake", "wear", "win", "worry",

    "able", "bad", "best", "better", "big", "black", "blue", "clear", "close", "cold", "common", "complete", "dark", "dead", "deep", "early", "easy", "empty", "equal", "extra", "fine", "free", "full", "fun", "happy", "hard", "hot", "human", "left", "live", "local", "low", "main", "major", "minute", "natural", "necessary", "nice", "open", "personal", "poor", "possible", "pretty", "prime", "proud", "quick", "quiet", "real", "red", "rich", "right", "slow", "special", "strong", "sure", "tall", "top", "total", "tough", "true", "warm", "whole", "wide", "wild", "wrong", "yellow", "young", "ago", "already", "almost", "especially", "eventually", "exactly", "finally", "forward", "hardly", "nearly", "neither", "normally", "otherwise", "perhaps", "probably", "quite", "rather", "really", "simply", "sometimes", "soon", "suddenly", "therefore", "thus", "together", "until", "whatever", "within", "yes",

    "account", "action", "activity", "age", "airport", "animal", "answer", "apartment", "article", "artist", "ball", "band", "bank", "bar", "base", "bath", "battle", "bed", "bit", "block", "blood", "board", "boat", "bone", "boss", "bottle", "box", "boyfriend", "bridge", "brother", "building", "bus", "cabinet", "camp", "campaign", "capital", "car", "card", "case", "cash", "cause", "cell", "chair", "challenge", "champion", "chapter", "chest", "child", "church", "circle", "club", "coast", "community", "company", "concert", "condition", "conference", "court", "cover", "cup", "customer", "daughter", "deal", "death", "debate", "decision", "department", "design", "desk", "development", "dinner", "direction", "disease", "doctor", "document", "door", "draft", "drama", "drawing", "driver", "earth", "economy", "education", "effect", "effort", "election", "emperor", "employee", "employer", "engine", "entry", "environment", "equipment", "error", "event", "exam", "experience", "expert", "expression", "eye", "fact", "factor", "failure", "family", "farm", "field", "figure", "film", "fire", "firm", "floor", "focus", "food", "foot", "function", "fund", "future", "garden", "gas", "gate", "generation", "glass", "goal", "god", "government", "green", "ground", "half", "hall", "hand", "head", "heart", "heat", "height", "hill", "history", "hole", "hospital", "hotel", "hour", "house", "husband", "image", "impact", "industry", "information", "injury", "instance", "insurance", "interest", "internet", "interview", "investment", "issue", "item", "job", "king", "kitchen", "knowledge", "lab", "lady", "lake", "land", "lawyer", "leader", "level", "library", "life", "light", "list", "loan", "location", "loss", "love", "machine", "magazine", "mail", "manager", "map", "market", "master", "material", "matter", "meal", "member", "memory", "message", "method", "middle", "minute", "model", "moment", "money", "month", "morning", "mother", "movie", "music", "nation", "nature", "news", "newspaper", "night", "noise", "north", "note", "number", "object", "office", "officer", "opinion", "opportunity", "option", "order", "page", "pain", "painting", "paper", "parent", "park", "part", "party", "patient", "pattern", "payment", "peace", "people", "percent", "period", "person", "phone", "photo", "picture", "piece", "place", "plan", "plant", "player", "point", "police", "policy", "population", "position", "power", "practice", "president", "price", "problem", "process", "product", "production", "program", "project", "property", "quality", "quarter", "question", "radio", "range", "rate", "reason", "record", "region", "relation", "relationship", "report", "research", "resource", "response", "rest", "result", "return", "river", "road", "rock", "role", "room", "rule", "safety", "sale", "scene", "school", "science", "screen", "search", "season", "seat", "second", "secret", "secretary", "section", "security", "sense", "series", "service", "shape", "share", "shirt", "shop", "show", "side", "sign", "sir", "sister", "site", "size", "skill", "skin", "society", "software", "son", "song", "sound", "source", "south", "space", "speaker", "special", "speech", "sport", "spring", "staff", "stage", "star", "state", "station", "status", "step", "stock", "store", "story", "street", "student", "study", "style", "subject", "success", "summer", "support", "system", "table", "task", "tax", "teacher", "technology", "television", "term", "test", "theater", "thing", "thought", "time", "title", "tool", "town", "trade", "tradition", "train", "transport", "travel", "trip", "trouble", "type", "university", "user", "value", "video", "view", "village", "virus", "voice", "volume", "war", "water", "way", "wealth", "week", "weight", "west", "wife", "wind", "window", "winter", "woman", "word", "work", "worker", "world", "writer", "year",

    "amber", "azure", "beige", "bronze", "brown", "charcoal", "coral", "crimson", "cyan", "emerald", "fuchsia", "gold", "gray", "green", "indigo", "ivory", "khaki", "lavender", "lime", "magenta", "maroon", "navy", "olive", "orange", "pink", "purple", "ruby", "salmon", "silver", "tan", "teal", "turquoise", "violet", "white", "yellow",

    "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday",
    "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December",
    "Spring", "Summer", "Fall", "Autumn", "Winter",

    "algorithm", "app", "application", "battery", "blog", "browser", "cloud", "code", "data", "database", "digital", "download", "email", "file", "framework", "gigabyte", "hardware", "interface", "keyboard", "laptop", "link", "login", "memory", "monitor", "mouse", "network", "online", "password", "profile", "server", "software", "stream", "tablet", "upload", "username", "video", "virtual", "website", "wifi",

    "anger", "anxiety", "awe", "boredom", "calm", "confusion", "contentment", "courage", "curiosity", "delight", "despair", "disgust", "doubt", "ecstasy", "embarrassment", "envy", "euphoria", "excitement", "gratitude", "grief", "guilt", "hatred", "homesickness", "loneliness", "nostalgia", "optimism", "panic", "passion", "pessimism", "pride", "rage", "regret", "relief", "remorse", "satisfaction", "shame", "shock", "surprise", "suspicion", "sympathy", "tension", "trust", "wonder",

    "analysis", "atom", "biology", "chemistry", "concept", "conclusion", "definition", "element", "energy", "equation", "experiment", "formula", "function", "gravity", "hypothesis", "logic", "mass", "method", "physics", "principle", "process", "proof", "psychology", "reaction", "theory", "thesis", "variable", "velocity", "volume",
];